let SalesInvoiceStrings = {
    SALES_INVOICE_URL: '/app/home/vouchers/invoice?voucher_type=0&voucher_category=sales',
    CREATE_SALES_INVOICE: 'Create  sales invoice',
    TEST_ENTERTPRISE: 'Test Enterprise',
    BILL_TO: ' Bill To ',
    CASH_DEFAULT: ' Set Cash Sale as default',
    ADD_PARTY: '+ Add Party Shift + Y',
    SALES_INVOICE_NUMBER: ' sales invoice No:   ',
    SALES_INVOICE_DATE: ' sales invoice Date:  ',
    PAYMENT_TERMS: ' Payment Terms:  ',
    DUE_DATE: ' Due Date:  ',
    ITEM_NO: 'No',
    ITEMS_SERVICES: ' Items/ Services ',
    HSN_SAC: ' HSN/ SAC ',
    QUANTITY: ' Qty ',
    PRICE_ITEM: ' Price/Item (₹) ',
    DISCOUNT: 'Discount',
    TAX: 'Tax',
    AMOUNT: 'Amount (₹)',
    SUBTOTAL: 'SUBTotal',
    TERMS_AND_CONDITION: ' Terms and Conditions ',
    TAXABLE_AMOUNT: 'Taxable Amount',
    TOTAL_AMOUNT: 'Total Amount',
    AMOUNT_RECEIVED: ' Amount Received ',
    BALANCE_AMOUNT: ' Balance Amount ',
    SIGNATURE_TEXT: 'Authorized signatory for Test Enterprise',
    PARTY_NAME: 'testParty',
    PARTY_MULTIPLE_ADDRESS: 'test_multiple address',
    BUSINESS_NAME: 'Test Enterprise ',
    BILL_ADDRESS: 'Address:',
    BILL_PHONE_NUMBER: 'Phone Number:',
    BILL_PAN_NUMBER: 'PAN Number:',
    BILL_GSTIN: 'GSTIN:',
    ADD_ITEM: 'Add Items',
    ITEM_NAME: 'Boat Rockerz 450',
    NEW_USER_SALES_INVOICE_PAGE_TEXT: ' No Sales Invoice made during the selected time period ',
    SALES_INVOICE_PAGE_URL: 'Sales Invoices',
    SALES_INVOICE_SUB_HEADER: ' Bill your sales to customers ',
    SECOND_PARTY: 'Raj',
    BATCH_NUMBER: ' Batch #1',
    ITEM_SERIAL_NUMBER: 'LE124152512',
    SERIAL_ITEM_NAME: 'Serial Item',

}
module.exports = SalesInvoiceStrings 